### ISSUE TITLE
La repo contiene username e password

### ISSUE THREAD

**Issue by spacefall** [Lioydiano/Classeviva#16]
Ti consiglio di toglierle e fai un force push per toglierla dai commit precedenti (magari cambia anche la password)

**Comment by FLAK-ZOSO** [comment]
Grazie mille, procedo subito, non ho idea del perché siano stati caricati su GitHub i file di testo, dopo che per mesi avevo sempre committato con lo stesso .gitignore che escludeva quei file di testo.

Anche cambiando il .gitignore i due file non se ne vanno, che skill issue che ho...
